- name: Workstation
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/auto-provisioning.yml
