- name: Workstation
  hosts: localhost
  connection: local
  become: true
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/auto-provisioning.yml
    - include_tasks: tasks/elasticsearch.yml
    - include_tasks: tasks/docker.yml
