- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install packages
  apt:
    name: '{{item}}'
  with_items:
    - htop
    - mc
    - tmux
    - jq # JSON formatter, json_pp alternative (json_pp doesn't support UTF-8)
