- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install packages
  apt:
    name: '{{item}}'
  with_items:
    # Required for Elasticsearch installation:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.8/deb.html#deb-repo
    - apt-transport-https
    - curl
    - docker-ce
    - docker-ce-cli
    - docker-compose
    # Tommy project requires Elasticsearch 6.8
    - elasticsearch=6.8.13
    - google-chrome-stable
    - google-drive-ocamlfuse
    - htop
    # JSON formatter
    # Alternative to json_pp (json_pp doesn't support UTF-8)
    - jq
    - keepass2
    - krusader
    - mc
    - mysql-server-8.0
    # Tommy project requires PHP 7.4
    - php7.4
    - php7.4-amqp
    - php7.4-cli
    - php7.4-curl
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-xdebug
    - php7.4-xml
    - php7.4-zip
    - php-amqp
    - php-pear
    - rabbitmq-server
    - ripgrep
    - slack
    - tmux
    - xmlcopyeditor
