- name: Add GPG keys
  apt_key:
    keyring: '{{ item.keyring }}'
    url: '{{ item.url }}'
  loop:
    - keyring: /etc/apt/trusted.gpg.d/rabbitmq.gpg
      url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    - keyring: /etc/apt/trusted.gpg.d/rabbitmq-packagecloud.gpg
      url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    # Erlang/OTP, required by RabbitMQ
    - keyring: /etc/apt/trusted.gpg.d/erlang.gpg
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc
- name: Add package repositories
  apt_repository:
    filename: '{{ item.filename }}'
    repo: '{{ item.repo }}'
  loop:
    - filename: rabbitmq
      repo: deb [arch={{ arch }}] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} main
    # Erlang/OTP, required by RabbitMQ
    - filename: erlang
      repo: deb [arch={{ arch }}] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ ansible_facts['distribution_release'] | lower }} main
