- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install Debian packages
  apt:
    name: '{{ item }}'
  loop:
    # Erlang required by RabbitMQ
    - erlang-asn1
    - erlang-base
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl
    - rabbitmq-server
