- name: Add GPG keys
  apt_key:
    keyring: '{{ item.keyring }}'
    url: '{{ item.url }}'
  loop:
    - keyring: /etc/apt/trusted.gpg.d/ngrok.gpg
      url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
- name: Add package repositories
  apt_repository:
    filename: '{{ item.filename }}'
    repo: '{{ item.repo }}'
  loop:
    - filename: php
      repo: ppa:ondrej/php

    - filename: git
      repo: ppa:git-core/ppa

    - filename: ngrok
      repo: deb [arch={{ arch }}] https://ngrok-agent.s3.amazonaws.com buster main
