- name: Add GPG keys
  apt_key:
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
- name: Add package repositories
  apt_repository:
    filename: virtualbox
    repo: deb [arch={{ arch }}] https://download.virtualbox.org/virtualbox/debian {{ ansible_facts['distribution_release'] | lower }} contrib
- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install Debian packages
  apt:
    name: '{{ item }}'
  loop:
    - virtualbox-6.1
