- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install base packages
  apt:
    name: '{{ item }}'
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
    - software-properties-common
- name: Add GPG keys
  apt_key:
    keyring: '{{ item.keyring }}'
    url: '{{ item.url }}'
  loop:
    - keyring: /etc/apt/trusted.gpg.d/docker.gpg
      url: https://download.docker.com/linux/ubuntu/gpg
    - keyring: /etc/apt/trusted.gpg.d/rabbitmq.gpg
      url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    - keyring: /etc/apt/trusted.gpg.d/rabbitmq-packagecloud.gpg
      url: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    # Erlang/OTP, required by RabbitMQ
    - keyring: /etc/apt/trusted.gpg.d/erlang.gpg
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc
    - keyring: /etc/apt/trusted.gpg.d/google.gpg
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    - keyring: /etc/apt/trusted.gpg.d/ngrok.gpg
      url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
- name: Retrieve system architecture
  shell: dpkg --print-architecture
  register: dpkg_print_architecture
  changed_when: false
- name: Add package repositories
  apt_repository:
    filename: '{{ item.filename }}'
    repo: '{{ item.repo }}'
  loop:
    - filename: ubuntu-main-restricted
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} main restricted
    - filename: ubuntu-main-restricted
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} main restricted
    - filename: ubuntu-main-restricted
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates main restricted
    - filename: ubuntu-main-restricted
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates main restricted
    - filename: ubuntu-main-restricted
      repo: deb [arch={{ arch }}] http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security main restricted
    - filename: ubuntu-main-restricted
      repo: deb-src http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security main restricted

    - filename: ubuntu-universe
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} universe
    - filename: ubuntu-universe
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} universe
    - filename: ubuntu-universe
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates universe
    - filename: ubuntu-universe
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates universe
    - filename: ubuntu-universe
      repo: deb [arch={{ arch }}] http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security universe
    - filename: ubuntu-universe
      repo: deb-src http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security universe

    - filename: ubuntu-multiverse
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} multiverse
    - filename: ubuntu-multiverse
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} multiverse
    - filename: ubuntu-multiverse
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates multiverse
    - filename: ubuntu-multiverse
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-updates multiverse
    - filename: ubuntu-multiverse
      repo: deb [arch={{ arch }}] http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security multiverse
    - filename: ubuntu-multiverse
      repo: deb-src http://security.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] | lower }}-security multiverse

    - filename: ubuntu-partner
      repo: deb [arch={{ arch }}] http://archive.canonical.com/ubuntu {{ ansible_facts['distribution_release'] | lower }} partner
    - filename: ubuntu-partner
      repo: deb-src http://archive.canonical.com/ubuntu {{ ansible_facts['distribution_release'] | lower }} partner

    - filename: ubuntu-backports
      repo: deb [arch={{ arch }}] http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-backports main restricted universe multiverse
    - filename: ubuntu-backports
      repo: deb-src http://archive.ubuntu.com/ubuntu/ {{ ansible_facts['distribution_release'] | lower }}-backports main restricted universe multiverse

    - filename: php
      repo: deb [arch={{ arch }}] http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_facts['distribution_release'] | lower }} main

    - filename: keepass
      repo: deb [arch={{ arch }}] http://ppa.launchpad.net/jtaylor/keepass/ubuntu {{ ansible_facts['distribution_release'] | lower }} main

    - filename: google-drive-ocamlfuse
      repo: deb [arch={{ arch }}] http://ppa.launchpad.net/alessandro-strada/ppa/ubuntu {{ ansible_facts['distribution_release'] | lower }} main

    - filename: docker
      repo: deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] | lower }} stable

    - filename: rabbitmq
      repo: deb [arch={{ arch }}] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_facts['distribution_release'] | lower }} main

    # Erlang/OTP, required by RabbitMQ
    - filename: erlang
      repo: deb [arch={{ arch }}] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ ansible_facts['distribution_release'] | lower }} main

    - filename: google-chrome
      repo: deb [arch={{ arch }}] http://dl.google.com/linux/chrome/deb/ stable main

    - filename: ngrok
      repo: deb [arch={{ arch }}] https://ngrok-agent.s3.amazonaws.com buster main
  vars:
    arch: '{{ dpkg_print_architecture.stdout }}'
