- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install Debian packages
  apt:
    name: '{{ item }}'
  loop:
    # Krusader icon problem: https://forum.kde.org/viewtopic.php?f=225&t=169954
    - breeze-icon-theme
    # Necessary for Gnome shell extensions (gnome-shell-extensions)
    - chrome-gnome-shell
    # Required for Docker:
    # https://docs.docker.com/engine/install/ubuntu/#install-docker-engine
    - containerd.io
    - curl
    - docker-ce
    - docker-ce-cli
    - docker-compose
    # Erlang required by RabbitMQ
    - erlang-asn1
    - erlang-base
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon
    - erlang-parsetools
    - erlang-public-key
    - erlang-runtime-tools
    - erlang-snmp
    - erlang-ssl
    - erlang-syntax-tools
    - erlang-tftp
    - erlang-tools
    - erlang-xmerl
    - filezilla
    - gedit-plugins
    - git
    # Install browser extension to install additional Gnome extensions
    # https://linuxconfig.org/how-to-install-gnome-shell-extensions-on-ubuntu-20-04-focal-fossa-linux-desktop
    - gnome-shell-extensions
    - gnome-tweaks
    - google-chrome-stable
    - google-drive-ocamlfuse
    - gufw
    - htop
    - iotop
    - jq
    - keepass2
    - krusader
    - mc
    - mysql-server-8.0
    - nethogs
    - ngrok
    - pavucontrol
    - php7.4
    - php7.4-amqp
    - php7.4-cli
    - php7.4-curl
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-xdebug
    - php7.4-xml
    - php7.4-zip
    - rabbitmq-server
    - ripgrep
    - slack
    - tmux
    - traceroute
    # Required by tmux mod
    - xclip
    - xmlcopyeditor
- name: Install Snap packages
  community.general.snap:
    name: '{{ item.name }}'
    classic: '{{ item.classic }}'
    channel: '{{ item.channel }}'
  loop:
    - { name: 'dbeaver-ce', classic: false, channel: ~ }
    - { name: 'mysql-workbench-community', classic: false, channel: ~ } # Unofficial
    # Node.js and npm
    - { name: 'node', classic: true, channel: '14/stable' }
    - { name: 'notepad-plus-plus', classic: false, channel: ~ } # Unofficial
    - { name: 'phpstorm', classic: true, channel: ~ }
    - { name: 'postman', classic: false, channel: ~ }
    - { name: 'slack', classic: true, channel: ~ }
