- include_tasks: add_package_repositories.yml
- include_tasks: install_packages.yml
- include_tasks: install_ubuntu_restricted_extras.yml
- include_tasks: configure_tmux.yml
- include_tasks: configure_docker.yml
# Tommy project requires Elasticsearch 6.8
- name: Install Elasticsearch 6.8
  include_role:
    name: elasticsearch_68
