- name: Add GPG keys
  apt_key:
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    url: https://download.docker.com/linux/ubuntu/gpg
- name: Add package repositories
  apt_repository:
    filename: docker
    repo: deb [arch={{ arch }}] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] | lower }} stable
