- name: Update package repositories
  apt:
    update_cache: yes
  changed_when: false
- name: Install Debian packages
  apt:
    name: '{{ item }}'
  loop:
    # BOX files access
    - filezilla
    - mysql-server-8.0
    - php7.4
    - php7.4-amqp
    - php7.4-cli
    - php7.4-curl
    - php7.4-gd
    - php7.4-intl
    - php7.4-mbstring
    - php7.4-mysql
    - php7.4-xdebug
    - php7.4-xml
    - php7.4-zip
- name: Install Snap packages
  community.general.snap:
    name: '{{ item.name }}'
    classic: '{{ item.classic }}'
    channel: '{{ item.channel }}'
  loop:
    # Node.js and npm
    - { name: 'node', classic: true, channel: '14/stable' }
